### PR TITLE
gatekeeper: update to the latest DPDK

### LINKED ISSUE #272: Update DPDK to properly support BPF
We are going to add BPF to Gatekeeper, but DPDK has two issues with BPF: [the verifier fails BPF code generated with clang 6.0 or higher](https://bugs.dpdk.org/show_bug.cgi?id=259) and [the verifier is vulnerable to malicious code](https://bugs.dpdk.org/show_bug.cgi?id=283).

Updating DPDK requires to update our DPDK patches, making our code conforms to any interface that may have changed, and test Gatekeeper.

### PR DESCRIPTION
**Pull request by mengxiang0811**
This pull request closes #272

### CODE REVIEW

**Comment by AltraMayor** [comment]
To which branch in [our DPDK repository](https://github.com/cjdoucette/dpdk/) is this pull request moving Gatekeeper? None of the branches "gatekeeper" and "gatekeeper2" seems to be what we talked about in our last Thursday meetup. This is critical because this pull request claims to close issue #272 and doesn't seem to do so.

It'd be nice to add a summary of the changes in the commit message. Example of items to add to this summary:
```
* Rename constant `ETHER_TYPE_IPv4` to `RTE_ETHER_TYPE_IPV4`
* Rename constant `ETHER_TYPE_IPv6` to `RTE_ETHER_TYPE_IPV6`
* Rename `struct arp_hdr` to `struct rte_arp_hdr`
```
This would quickly make someone like Cody aware of the changes between DPDK's versions. Instead of requiring taking a look into the patch to find that out.

**Comment by mengxiang0811** [comment]
This rebase is ready for review. Note that, the fix for [the verifier is vulnerable to malicious code](https://bugs.dpdk.org/show_bug.cgi?id=283) issue has not been addressed, although it's a small fix. I will track this issue.

**Comment by AltraMayor** [comment]
What about a way to compile DPDK with `CONFIG_RTE_LIBRTE_BPF_ELF=y`?

**Comment by mengxiang0811** [comment]
The patch has been added back now.

**Pull request merged**
